AllCops:
  NewCops: enable
  TargetRubyVersion: 4.0
  SuggestExtensions: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Naming/MethodParameterName:
  AllowedNames:
    - ir

Lint/DataDefineOverride:
  Enabled: false

Layout/LineLength:
  Max: 150

Metrics/AbcSize:
  Max: 25

Metrics/ClassLength:
  Max: 180

Metrics/ModuleLength:
  Exclude:
    - "lib/generator/contracts.rb"

Style/HashSyntax:
  EnforcedShorthandSyntax: always

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/MethodLength:
  Max: 20

Metrics/PerceivedComplexity:
  Max: 10

Metrics/ParameterLists:
  Max: 6

Metrics/BlockLength:
  Exclude:
    - "test/**/*"
